services:
  aarhusspaceprogramapi:
    image: aarhusspaceprogramapi
    build:
      context: .
      dockerfile: AarhusSpaceProgramAPI/Dockerfile
    ports:
      - "5265:5265"
    depends_on:
      mongodb: 
        condition: service_started
      sqlserver:
        condition: service_healthy
          

  generatemissionlogs:
    image: generatemissionlogs
    build:
      context: .
      dockerfile: GenerateMissionLogs/Dockerfile
    depends_on:
      - mongodb
      - aarhusspaceprogramapi

  mongodb:
    image: mongo:8.3.1
    ports:
      - "27017:27017"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Chris132"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "Chris132!" -Q "SELECT 1" -b -o /dev/null -C
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s