// <auto-generated />
using System;
using AarhusSpaceProgramAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AarhusSpaceProgramAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AarhusSpaceProgramAPI.Models.Astronaut", b =>
                {
                    b.Property<int>("AstronautId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AstronautId"));

                    b.Property<double>("EXPInSim")
                        .HasColumnType("float");

                    b.Property<double>("EXPInSpace")
                        .HasColumnType("float");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PayGrade")
                        .HasColumnType("float");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AstronautId");

                    b.ToTable("Astronauts");
                });

            modelBuilder.Entity("AarhusSpaceProgramAPI.Models.CelestialBody", b =>
                {
                    b.Property<int>("CelestialBodyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CelestialBodyId"));

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Composition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentPlanetId")
                        .HasColumnType("int");

                    b.HasKey("CelestialBodyId");

                    b.HasIndex("ParentPlanetId");

                    b.ToTable("CelestialBodies");
                });

            modelBuilder.Entity("AarhusSpaceProgramAPI.Models.Experiment", b =>
                {
                    b.Property<int>("ExperimentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExperimentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExperimentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MissionId")
                        .HasColumnType("int");

                    b.Property<int?>("ScientistId")
                        .HasColumnType("int");

                    b.HasKey("ExperimentId");

                    b.HasIndex("MissionId");

                    b.HasIndex("ScientistId");

                    b.ToTable("Experiment");
                });

            modelBuilder.Entity("AarhusSpaceProgramAPI.Models.LaunchPad", b =>
                {
                    b.Property<int>("LaunchPadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LaunchPadId"));

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MaxWeight")
                        .HasColumnType("float");

                    b.HasKey("LaunchPadId");

                    b.ToTable("LaunchPads");
                });

            modelBuilder.Entity("AarhusSpaceProgramAPI.Models.Manager", b =>
                {
                    b.Property<int>("ManagerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManagerId"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ManagerId");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("AarhusSpaceProgramAPI.Models.Mission", b =>
                {
                    b.Property<int>("MissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MissionId"));

                    b.Property<double>("Duration")
                        .HasColumnType("float");

                    b.Property<DateTime>("LaunchDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LaunchPadId")
                        .HasColumnType("int");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("MissionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RocketId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TargetBodyId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MissionId");

                    b.HasIndex("LaunchPadId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("RocketId")
                        .IsUnique()
                        .HasFilter("[RocketId] IS NOT NULL");

                    b.HasIndex("TargetBodyId");

                    b.ToTable("Missions");
                });

            modelBuilder.Entity("AarhusSpaceProgramAPI.Models.Rocket", b =>
                {
                    b.Property<int>("RocketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RocketId"));

                    b.Property<int>("CrewCapacity")
                        .HasColumnType("int");

                    b.Property<double>("FuelCapacity")
                        .HasColumnType("float");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PayloadCapacity")
                        .HasColumnType("float");

                    b.Property<int>("Stages")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("RocketId");

                    b.ToTable("Rockets");
                });

            modelBuilder.Entity("AarhusSpaceProgramAPI.Models.Scientist", b =>
                {
                    b.Property<int>("ScientistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScientistId"));

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ScientistId");

                    b.ToTable("Scientists");
                });

            modelBuilder.Entity("AstronautMission", b =>
                {
                    b.Property<int>("AstronautsAstronautId")
                        .HasColumnType("int");

                    b.Property<int>("MissionsMissionId")
                        .HasColumnType("int");

                    b.HasKey("AstronautsAstronautId", "MissionsMissionId");

                    b.HasIndex("MissionsMissionId");

                    b.ToTable("AstronautMission");
                });

            modelBuilder.Entity("MissionScientist", b =>
                {
                    b.Property<int>("MissionsMissionId")
                        .HasColumnType("int");

                    b.Property<int>("ScientistsScientistId")
                        .HasColumnType("int");

                    b.HasKey("MissionsMissionId", "ScientistsScientistId");

                    b.HasIndex("ScientistsScientistId");

                    b.ToTable("MissionScientist");
                });

            modelBuilder.Entity("AarhusSpaceProgramAPI.Models.CelestialBody", b =>
                {
                    b.HasOne("AarhusSpaceProgramAPI.Models.CelestialBody", "ParentPlanet")
                        .WithMany("Moons")
                        .HasForeignKey("ParentPlanetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentPlanet");
                });

            modelBuilder.Entity("AarhusSpaceProgramAPI.Models.Experiment", b =>
                {
                    b.HasOne("AarhusSpaceProgramAPI.Models.Mission", "Mission")
                        .WithMany("Experiments")
                        .HasForeignKey("MissionId");

                    b.HasOne("AarhusSpaceProgramAPI.Models.Scientist", "Scientist")
                        .WithMany()
                        .HasForeignKey("ScientistId");

                    b.Navigation("Mission");

                    b.Navigation("Scientist");
                });

            modelBuilder.Entity("AarhusSpaceProgramAPI.Models.Mission", b =>
                {
                    b.HasOne("AarhusSpaceProgramAPI.Models.LaunchPad", "LaunchPad")
                        .WithMany("Missions")
                        .HasForeignKey("LaunchPadId");

                    b.HasOne("AarhusSpaceProgramAPI.Models.Manager", "Manager")
                        .WithMany("Missions")
                        .HasForeignKey("ManagerId");

                    b.HasOne("AarhusSpaceProgramAPI.Models.Rocket", "Rocket")
                        .WithOne("mission")
                        .HasForeignKey("AarhusSpaceProgramAPI.Models.Mission", "RocketId");

                    b.HasOne("AarhusSpaceProgramAPI.Models.CelestialBody", "TargetBody")
                        .WithMany("Missions")
                        .HasForeignKey("TargetBodyId");

                    b.Navigation("LaunchPad");

                    b.Navigation("Manager");

                    b.Navigation("Rocket");

                    b.Navigation("TargetBody");
                });

            modelBuilder.Entity("AstronautMission", b =>
                {
                    b.HasOne("AarhusSpaceProgramAPI.Models.Astronaut", null)
                        .WithMany()
                        .HasForeignKey("AstronautsAstronautId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AarhusSpaceProgramAPI.Models.Mission", null)
                        .WithMany()
                        .HasForeignKey("MissionsMissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MissionScientist", b =>
                {
                    b.HasOne("AarhusSpaceProgramAPI.Models.Mission", null)
                        .WithMany()
                        .HasForeignKey("MissionsMissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AarhusSpaceProgramAPI.Models.Scientist", null)
                        .WithMany()
                        .HasForeignKey("ScientistsScientistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AarhusSpaceProgramAPI.Models.CelestialBody", b =>
                {
                    b.Navigation("Missions");

                    b.Navigation("Moons");
                });

            modelBuilder.Entity("AarhusSpaceProgramAPI.Models.LaunchPad", b =>
                {
                    b.Navigation("Missions");
                });

            modelBuilder.Entity("AarhusSpaceProgramAPI.Models.Manager", b =>
                {
                    b.Navigation("Missions");
                });

            modelBuilder.Entity("AarhusSpaceProgramAPI.Models.Mission", b =>
                {
                    b.Navigation("Experiments");
                });

            modelBuilder.Entity("AarhusSpaceProgramAPI.Models.Rocket", b =>
                {
                    b.Navigation("mission")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
